### ISSUE TITLE
question about montecarlo script

### ISSUE THREAD

**Issue by Cebrian007** [north-road/qgis-processing-r#132]
Hello everyone,

The library maptools was needed to run the montecarlo script, but this library has been removed from Cran. My question is if in the latest version of the plugin maptools is still needed to run the script montecarlo or the script has been updated and uses other libraries.

Many thanks in advance.

All the best,

David

**Comment by JanCaha** [comment]
If you use the package in the script then yes, you need that package. Since maptools have been officially removed along with some other packages like rgdal, it is best to rewrite the script using other packages - like sp, sf and whatever else you need. 

You could probably install maptools from CRAN archive sources, but quite likely you will run into dependency issues. I understand that it is not what one would like to do, but things like that really ask for rewriting the stuff using more up to date packages.

**Comment by Cebrian007** [comment]
Many thanks for your answer @JanCaha
